
# Configurable parameter settings.

AGENTS.PER.COHORT <- 100
AGENT.FREQUENCIES <- c(rational=.1, imitative=.85, random=.05)
IMITATION.THRESHOLD <- .5
SOCIAL.NETWORK.SIZE.RANGE <- c(10,25)
SOCIAL.NETWORK.EXTENT <- c(0,5)
DEATH.AGE.RANGE <- c(60,100)
RANDOM.AGENTS.RET.PROB <- .5
AGE.OF.RETIREMENT.ELIGIBILITY <- 65
AGE.OF.FORCED.RETIREMENT <- Inf
